### ISSUE TITLE
Deploying this docker results in the nginx Welcome page on port 80

### ISSUE THREAD

**Issue by TestingBytes** [bcleonard/calibre-cops#1]
I tried deploying this docker on my synology and the nginx welcome page is displayed on port 80. Is there an extra step required to get cops setup?

**Comment by bcleonard** [comment]
Yes.  Its <server-name>/apps.  I need to update the docs.  I would like to have it in the root, but this was my first attempt at it.  FYI, for some reason the cronjob to add the books is not working.

**Comment by TestingBytes** [comment]
Thanks, I see the updated docs, I'll give it a try.
